#!/usr/bin/env bash
set -o errexit -o errtrace -o functrace -o nounset -o pipefail

# Where to put buildctl if it's not in the path
BIN_LOCATION="$HOME/Projects/Command/bin"
BUILDKIT_IMAGE="dubodubonduponey/buildkit"
BUILDCTL_IMAGE="dubodubonduponey/buildkit"

# shellcheck source=/dev/null
root="$(cd "$(dirname "${BASH_SOURCE[0]:-$PWD}")" 2>/dev/null 1>&2 && pwd)/../"

setup::docker(){
  if ! command -v docker > /dev/null; then
    >&2 printf "You need to install docker on your system\n"
    return 1
  fi
}

setup::cue(){
  if ! command -v cue > /dev/null; then
    case $(uname) in
      "Darwin")
        if command -v brew; then
          echo "You miss the cue binary. We can install that for you using brew. Press enter if you want that, CTRL+C otherwise."
          read -r
          brew install cue
          return
        fi
      ;;
    esac
    echo "You need to install cue on your system: https://cuelang.org/docs/install/"
    return 1
  fi
}

setup::buildctl(){
  local destination="$1"
  if ! command -v "$destination/buildctl" > /dev/null; then
    mkdir -p "$destination"
    docker rm -f installbuildctl || true
    docker run --name installbuildctl --entrypoint buildctl "$BUILDCTL_IMAGE" --version
    case $(uname) in
      "Darwin")
        docker cp installbuildctl:/boot/bin/buildctl_mac "$destination/buildctl"
      ;;
      "Linux")
        docker cp installbuildctl:/boot/bin/buildctl "$destination/buildctl"
      ;;
      *)
        >&2 printf "You need to install buildctl on your system: https://github.com/moby/buildkit#quick-start and copy it in %s\n" "$destination"
        return 1
      ;;
    esac
    docker rm -f installbuildctl
  fi
}

setup::buildkit(){
  docker inspect dbdbdp-buildkit 1>/dev/null 2>&1 || \
    docker run --rm \
      -d -p 4242:4242 \
      --name dbdbdp-buildkit \
      --user root \
      --entrypoint buildkitd \
      --privileged \
      "$BUILDKIT_IMAGE" \
        --root /data/buildkit --addr tcp://0.0.0.0:4242
#      --read-only \
}

# Automated metadata
LICENSE="$(head -n 1 "$root/LICENSE")"

# https://tools.ietf.org/html/rfc3339
# XXX it doesn't seem like BSD date can format the timezone appropriately according to RFC3339 - eg: %:z doesn't work and %z misses the colon, so the gymnastic here
# This is date now
#DATE="$(date +%Y-%m-%dT%T%z | sed -E 's/([0-9]{2})([0-9]{2})$/\1:\2/')"
# This is last commit date - a much better date actually...
DATE="$(date -r "$(git -C "$root" log -1 --format="%at")" +%Y-%m-%dT%T%z 2>/dev/null || date --date="@$(git -C "$root" log -1 --format="%at")" +%Y-%m-%dT%T%z | sed -E 's/([0-9]{2})([0-9]{2})$/\1:\2/')"

VERSION="$(git -C "$root" describe --match 'v[0-9]*' --dirty='.m' --always)"
REVISION="$(git -C "$root" rev-parse HEAD)$(if ! git -C "$root" diff --no-ext-diff --quiet --exit-code; then printf ".m\\n"; fi)"
# XXX this is dirty, resolve ssh aliasing to github by default
URL="$(git -C "$root" remote show -n origin | grep "Fetch URL")"
URL="${URL#*Fetch URL: }"
URL="$(printf "%s" "$URL" | sed -E 's,.git$,,' | sed -E 's,^[a-z-]+:([^/]),https://github.com/\1,')"

export BUILD_LICENSES="$LICENSE"
export BUILD_CREATED="$DATE"
export BUILD_VERSION="$VERSION"
export BUILD_REVISION="$REVISION"
export BUILD_URL="$URL"

case "${1:-}" in
  "--version")
    exit
  ;;
  *)
    setup::docker
    setup::cue
    setup::buildctl "$BIN_LOCATION"

    # Setup buildkitd container optionally
    if [ ! "${BUILDKIT_HOST:-}" ]; then
      BUILDKIT_HOST=tcp://0.0.0.0:4242
      setup::buildkit
    fi
    export BUILDKIT_HOST

    target="${1:-image}"
    shift || true

    cd "$root"
    com=(cue "$@" "$target" "$root/hack/frontends/bake_tool.cue" "$root/hack/frontends/dbdbdp_tool.cue" "$root/bake_tool.cue")
    >&2 printf "Debug, will do: %s\n" "BUILDKIT_HOST=$BUILDKIT_HOST ${com[*]}"
    "${com[@]}" || {
      cd - > /dev/null
      echo "Execution failure"
      exit 1
    }
    cd - > /dev/null
  ;;
esac
